version: "3.8"
services:
  postgres:
    platform: linux/amd64
    image: postgres@sha256:fbcec7ba704eb8c846b2a265953fa8faaa562fb172e6670018e35da77ef06057
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-admin123}
      PGDATA: /data/zenoai/postgres
    volumes:
      - postgres:/data/zenoai/postgres
    ports:
      - "5432:5432"

volumes:
  cache:
    driver: local
  postgres:
    driver: local
